### ISSUE TITLE
Make this as a cf plugin

### ISSUE THREAD

**Issue by mike1808** [dmikusa-pivotal/top-logs#5]
Did you consider making this tool as a cf plugin?

**Comment by dmikusa-pivotal** [comment]
Probably unlikely to happen as this isn't really tied to CF. I do use it a lot with CF, but I use it elsewhere as well. I think you also have to write cf plugins in Golang.

I do want to adjust `top-logs` to read from stdin & read the `cf logs` format so that you can `cf logs my-app | top-logs` and have it directly parse logs. Issue for that is https://github.com/dmikusa-pivotal/top-logs/issues/3.
